version: '3'
services:
 web:
   container_name: my-restaurant-hub
   build: .
   command: python3 manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 18000:8000
   volumes:
     - .:/code
   depends_on:
     - db
 db:
   container_name: restaurant
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: restaurant
     MYSQL_USER: root
     MYSQL_PASSWORD: root
     MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
   volumes:
     - ./mysql:/var/lib/mysql
   ports:
     - 33306:3306